version: '3'
services:
  prom-client:
    build: client
    image: prom-client:latest
    deploy:
      replicas: 2
    networks:
    - prom-demo
  prom-server:
    build: server
    image: prom-server:latest
    ports:
    - "9090:9090"
    deploy:
      replicas: 1
    networks:
    - prom-demo

networks:
  prom-demo:
    driver: overlay

